# Lecture 7: DQN

## 링크
- https://www.youtube.com/watch?v=S1Y9eys2bdg&feature=youtu.be
- DQN paper : www.nature.com/articles/nature14236
- DQN source code: www.sites.google.com/a/deepmind.com/dqn/



## Q-function Approximation: Q-Nets

## Convergence

$\hat{Q}$ denote learner's current approximation to $Q$

## Two big issues
- But `diverges` using neural networks due to:
  - Correlations between samples
  - Non-stationary targets

## DQN's three solutions

1. Go deep
2. Capture and replay
  - Correlations between samples
3. Separate networks: create a target network
  - Non-stationary targets

# Lab 7-1: DQN 1 (NIPS 2013)

- youtube: https://www.youtube.com/watch?v=Fbf9YUyDFww&feature=youtu.be

## Code review acknowledgement
- Reference implementations
  - https://github.com/awjuliani/DeepRL-Agents
  - https://github.com/devsisters/DQN-tensorflow
  - https://github.com/dennybritz/reinforcement-learning/blob/master/DQN/dqn.py

In [3]:
## np.vstack
import numpy as np
a = np.arange(5)
b = np.arange(5, 10)
c = np.arange(10,15)
print(a)
print(b)
x = np.vstack([a,b])
print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


# Lab 7-2: DQN 2 (Nature 2015)

- Youtube: https://www.youtube.com/watch?v=ByB49iDMiZE
- Simple block based car race?
  - https://github.com/golbin/TensorFlow-Tutorials/tree/master/07%20-%20DQN
- DQN implementations
  - https://github.com/songrotek/DQN-Atari-Tensorflow
  - https://github.com/dennybritz/reinforcement-learning/blob/master/DQN/dqn.py
  - https://github.com/devsisters/DQN-tensorflow
- Other games
  - http:/www.ehrenbrav.com/2016/08/teaching-your-computer-to-play-super-mario-bros-a-fork-of-the-google-deepmind-atari-machine-learning-project/
- RMA approach
  - Run
  - Modify
  - Adapt (to your new game/problems)